"""Parse SRW-native Python scripts (varParam + set_optics style) into simplified beamline JSON.

SRW beamline scripts generated by Sirepo or hand-written follow a standard pattern:
- A ``varParam`` list of ``[name, type_char, default_value, description, ...]`` entries
  encoding all source, undulator, electron-beam, optics, and propagation parameters.
- A ``set_optics(v, names)`` function that constructs SRW optical elements from ``v``.
- Element names are ordered by their appearance in the ``names`` list and in the
  propagation-parameter (``_pp``) entries of ``varParam``.

This module converts that representation into the simplified JSON format used by the
MCP server (see ``docs/beamline-json-format.md``).
"""

from __future__ import annotations

import math
import re
from pathlib import Path
from typing import Any


def parse_srw_script(path: Path) -> dict:
    """Execute an SRW-native Python script and convert to simplified beamline JSON.

    The script is executed in an isolated namespace.  We look for ``varParam``
    (the standard parameter list) and optionally a ``names`` list or
    ``set_optics`` function to determine element ordering.

    Returns a dict with keys ``source``, ``elements``, and optionally
    ``_propagation_params`` (per-element SRW 17-element arrays converted to
    our 5-parameter format) and ``_raw_propagation_params`` (the original
    17-element arrays for lossless round-tripping).
    """
    source_text = path.read_text()
    namespace: dict[str, Any] = {}

    # Execute to extract varParam — but stub out heavy SRW imports and main()
    # so the script doesn't actually run a simulation.
    safe_source = _stub_srw_execution(source_text)
    exec(compile(safe_source, str(path), "exec"), namespace)  # noqa: S102

    var_param = namespace.get("varParam")
    if var_param is None:
        raise ValueError(f"No varParam found in {path}")

    return convert_varParam(var_param, source_text)


def convert_varParam(var_param: list, source_text: str = "") -> dict:
    """Convert an SRW ``varParam`` list to simplified beamline JSON.

    Args:
        var_param: The SRW parameter list (list of lists).
        source_text: Optional original script source for element-order extraction.
    """
    params = _flatten_varParam(var_param)

    # Extract ordered element names from the _pp entries (preserves beamline order)
    element_names = _extract_element_names(var_param)

    source = _extract_source(params)
    elements = [_extract_element(name, params) for name in element_names]
    elements = [e for e in elements if e is not None]

    # Propagation parameters
    prop_params = {}
    raw_prop_params = {}
    for name in element_names:
        pp_key = f"op_{name}_pp"
        if pp_key in params:
            pp_array = params[pp_key]
            if isinstance(pp_array, list) and len(pp_array) >= 9:
                prop_params[name] = _srw_pp_to_simplified(pp_array)
                raw_prop_params[name] = pp_array

    # Final propagation params
    if "op_fin_pp" in params:
        pp_array = params["op_fin_pp"]
        if isinstance(pp_array, list) and len(pp_array) >= 9:
            prop_params["_final"] = _srw_pp_to_simplified(pp_array)
            raw_prop_params["_final"] = pp_array

    result: dict[str, Any] = {
        "source": source,
        "elements": elements,
    }
    if prop_params:
        result["_propagation_params"] = prop_params
    if raw_prop_params:
        result["_raw_propagation_params"] = raw_prop_params

    return result


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _flatten_varParam(var_param: list) -> dict[str, Any]:
    """Build a flat ``{name: value}`` dict from the varParam list."""
    params: dict[str, Any] = {}
    for entry in var_param:
        if isinstance(entry, (list, tuple)) and len(entry) >= 3:
            params[entry[0]] = entry[2]
    return params


def _extract_element_names(var_param: list) -> list[str]:
    """Extract ordered element names from ``op_*_pp`` entries in varParam."""
    names: list[str] = []
    for entry in var_param:
        if not isinstance(entry, (list, tuple)) or len(entry) < 1:
            continue
        key = entry[0]
        if key.startswith("op_") and key.endswith("_pp") and key != "op_fin_pp":
            el_name = key[3:-3]  # strip 'op_' and '_pp'
            names.append(el_name)
    return names


def _get_element_params(el_name: str, params: dict) -> dict[str, Any]:
    """Collect all ``op_{el_name}_*`` parameters (excluding ``_pp``)."""
    prefix = f"op_{el_name}_"
    el_params: dict[str, Any] = {}
    for key, val in params.items():
        if key.startswith(prefix) and not key.endswith("_pp"):
            param_name = key[len(prefix):]
            el_params[param_name] = val
    return el_params


def _detect_mirror_orientation(el_params: dict) -> str:
    """Determine mirror orientation from normal-vector components.

    If |nvy| > |nvx| the mirror deflects vertically; otherwise horizontally.
    """
    nvx = abs(el_params.get("nvx", 0))
    nvy = abs(el_params.get("nvy", 0))
    return "vertical" if nvy > nvx else "horizontal"


def _extract_element(el_name: str, params: dict) -> dict | None:
    """Convert one element's parameters to simplified JSON."""
    el = _get_element_params(el_name, params)
    if not el:
        return None

    # Drift — has 'L' (length) and no mirror/crystal params
    if "L" in el and "d_sp" not in el and "ang" not in el:
        return {
            "type": "drift",
            "label": el_name,
            "length_m": el["L"],
        }

    # CRL — has 'delta' (refractive index decrement) and 'r_min' (tip radius)
    # Must check before aperture since CRLs also have a 'shape' parameter
    if "delta" in el and "r_min" in el:
        return _extract_crl(el_name, el)

    # Lens — has 'Fx' or 'Fy' (focal lengths)
    if "Fx" in el or "Fy" in el:
        fx = el.get("Fx", 1e23)
        fy = el.get("Fy", 1e23)
        return {
            "type": "lens",
            "label": el_name,
            "fx": fx,
            "fy": fy,
            "focal_length_m": fx if fx == fy else None,
        }

    # Aperture — has 'shape' (and is not a CRL which was checked above)
    if "shape" in el and "d_sp" not in el:
        shape_map = {"r": "rectangular", "c": "circular"}
        return {
            "type": "aperture",
            "label": el_name,
            "shape": shape_map.get(el["shape"], el["shape"]),
            "size_x_m": el.get("Dx", 0.001),
            "size_y_m": el.get("Dy", 0.001),
            "offset_x_m": el.get("x", 0.0),
            "offset_y_m": el.get("y", 0.0),
        }

    # Crystal — has 'd_sp' (d-spacing)
    if "d_sp" in el:
        elem: dict[str, Any] = {
            "type": "crystal",
            "label": el_name,
            "d_spacing_A": el["d_sp"],
            "psi0r": el.get("psi0r", 0),
            "psi0i": el.get("psi0i", 0),
            "psiHr": el.get("psiHr", 0),
            "psiHi": el.get("psiHi", 0),
            "psiHBr": el.get("psiHBr", 0),
            "psiHBi": el.get("psiHBi", 0),
            "thickness_m": el.get("tc", 0.01),
            "asymmetry_angle_rad": el.get("ang_as", 0.0),
            "use_case": int(el.get("uc", 1)),
            "energy_eV": el.get("energy", 10000),
            "diffraction_angle_rad": el.get("diffractionAngle", 0),
        }
        # Preserve explicit orientation vectors for crystals (DCM pairs
        # have opposite normal vector signs that can't be derived from
        # a single grazing angle + orientation string).
        if "nvx" in el:
            elem["nvx"] = el["nvx"]
            elem["nvy"] = el.get("nvy", 0)
            elem["nvz"] = el["nvz"]
            elem["tvx"] = el["tvx"]
            elem["tvy"] = el.get("tvy", 0)
        if "ang" in el:
            elem["grazing_angle_rad"] = el["ang"]
        return elem

    # Elliptical mirror — has 'p' (object distance) and 'q' (image distance)
    if "p" in el and "q" in el:
        orientation = _detect_mirror_orientation(el)
        return {
            "type": "mirror",
            "label": el_name,
            "subtype": "elliptical",
            "orientation": orientation,
            "object_distance_m": el["p"],
            "image_distance_m": el["q"],
            "grazing_angle_mrad": el.get("ang", 0.003) * 1000,
            "tangential_size_m": el.get("size_x", el.get("size_tang", 0.4)),
            "sagittal_size_m": el.get("size_y", el.get("size_sag", 0.02)),
        }

    # Height-profile mirror — has 'hfn' (height profile file) and 'ang'
    if "hfn" in el and "ang" in el:
        return {
            "type": "mirror",
            "label": el_name,
            "subtype": "height_profile",
            "height_profile_file": el["hfn"],
            "orientation": el.get("dim", "x"),
            "grazing_angle_rad": abs(el["ang"]),
            "grazing_angle_mrad": abs(el["ang"]) * 1000,
            "height_amplification": el.get("amp_coef", 1.0),
            "tangential_size_m": el.get("size_x", el.get("size_tang", 0.4)),
            "sagittal_size_m": el.get("size_y", el.get("size_sag", 0.02)),
        }

    # If we get here with 'ang' (grazing angle) it's likely a flat mirror
    if "ang" in el:
        orientation = _detect_mirror_orientation(el)
        return {
            "type": "mirror",
            "label": el_name,
            "subtype": "flat",
            "orientation": orientation,
            "grazing_angle_mrad": el["ang"] * 1000,
            "tangential_size_m": el.get("size_x", el.get("size_tang", 0.4)),
            "sagittal_size_m": el.get("size_y", el.get("size_sag", 0.02)),
        }

    return None


def _extract_crl(el_name: str, el: dict) -> dict:
    """Extract a CRL element from its parameters.

    CRL parameters from SRW:
        foc_plane: focusing plane (1=vertical, 2=horizontal, 3=both)
        delta: refractive index decrement
        atten_len: attenuation length [m]
        shape: lens shape (1=parabolic, 2=circular)
        apert_h: horizontal aperture [m]
        apert_v: vertical aperture [m]
        r_min: tip radius [m]
        n: number of lenses
        wall_thick: wall thickness at tip [m]

    Single-lens focal length: f = R / (2 * delta)
    Effective focal length for N lenses: f_eff = f_single / N
    """
    r_min = el["r_min"]
    delta = el["delta"]
    n_lenses = int(el.get("n", 1))
    foc_plane = int(el.get("foc_plane", 3))

    single_f = r_min / (2 * delta) if delta > 0 else 1e23
    effective_f = single_f / n_lenses if n_lenses > 0 else single_f

    # Determine fx, fy based on focusing plane
    # SRW convention: 1=horizontal, 2=vertical, 3=both
    if foc_plane == 1:
        fx, fy = effective_f, 1e23
    elif foc_plane == 2:
        fx, fy = 1e23, effective_f
    else:
        fx, fy = effective_f, effective_f

    apert_h = el.get("apert_h", 0.001)
    apert_v = el.get("apert_v", 0.001)

    return {
        "type": "crl",
        "label": el_name,
        "foc_plane": foc_plane,
        "n_lenses": n_lenses,
        "single_lens_focal_length_m": single_f,
        "focal_length_m": effective_f,
        "fx": fx,
        "fy": fy,
        "tip_radius_m": r_min,
        "delta": delta,
        "attenuation_length_m": el.get("atten_len", 1.0),
        "aperture_h_m": apert_h,
        "aperture_v_m": apert_v,
        "wall_thickness_m": el.get("wall_thick", 0.0),
        "shape": int(el.get("shape", 1)),
        "offset_x_m": el.get("x", 0.0),
        "offset_y_m": el.get("y", 0.0),
    }


def _extract_source(params: dict) -> dict:
    """Build the source definition from electron-beam and undulator parameters."""
    source: dict[str, Any] = {"type": "undulator"}

    # Photon energy
    if "w_e" in params:
        source["energy_eV"] = params["w_e"]

    # Electron beam
    if "ebm_e" in params:
        source["electron_energy_GeV"] = params["ebm_e"]
    if "ebm_i" in params:
        source["beam_current_A"] = params["ebm_i"]

    # Undulator
    und_per = params.get("und_per", 0.02)
    source["undulator_period_m"] = und_per
    if "und_len" in params:
        source["num_periods"] = int(round(params["und_len"] / und_per))

    # K parameter from peak magnetic field: K = 0.9338 * B[T] * lambda_u[cm]
    und_by = params.get("und_by", 0)
    und_bx = params.get("und_bx", 0)
    if und_by:
        source["K_vertical"] = 0.9338 * und_by * (und_per * 100)
    if und_bx:
        source["K_horizontal"] = 0.9338 * und_bx * (und_per * 100)

    # Field symmetry: 1=symmetric (cos), -1=anti-symmetric (sin)
    source["symmetry_vertical"] = int(params.get("und_sy", -1))
    source["symmetry_horizontal"] = int(params.get("und_sx", 1))

    # Electron beam initial z position
    _set_if(source, params, "ebm_z", "initial_z_m")

    # Extended electron beam parameters
    _set_if(source, params, "ebm_ens", "energy_spread")
    _set_if(source, params, "ebm_emx", "emittance_x_m")
    _set_if(source, params, "ebm_emy", "emittance_y_m")
    _set_if(source, params, "ebm_sigx", "beam_size_x_m")
    _set_if(source, params, "ebm_sigy", "beam_size_y_m")
    _set_if(source, params, "ebm_sigxp", "beam_divergence_x_rad")
    _set_if(source, params, "ebm_sigyp", "beam_divergence_y_rad")
    _set_if(source, params, "ebm_mxxp", "mixed_moment_xxp")
    _set_if(source, params, "ebm_myyp", "mixed_moment_yyp")
    _set_if(source, params, "ebm_x", "beam_center_x_m")
    _set_if(source, params, "ebm_y", "beam_center_y_m")
    _set_if(source, params, "ebm_xp", "beam_angle_x_rad")
    _set_if(source, params, "ebm_yp", "beam_angle_y_rad")
    _set_if(source, params, "ebm_dr", "longitudinal_drift_m")
    _set_if(source, params, "ebm_de", "energy_deviation_GeV")

    # First optic position (useful for observation distance)
    if "op_r" in params:
        source["first_optic_distance_m"] = params["op_r"]

    # Wavefront mesh settings
    mesh: dict[str, Any] = {}
    if "w_nx" in params:
        mesh["nx"] = int(params["w_nx"])
    if "w_ny" in params:
        mesh["ny"] = int(params["w_ny"])
    if "w_rx" in params:
        mesh["range_x_m"] = params["w_rx"]
    if "w_ry" in params:
        mesh["range_y_m"] = params["w_ry"]
    if "w_smpf" in params:
        source["sampling_factor"] = params["w_smpf"]
    if mesh:
        source["_mesh_params"] = mesh

    return source


def _set_if(target: dict, params: dict, src_key: str, dst_key: str) -> None:
    """Set ``target[dst_key] = params[src_key]`` if the source key exists."""
    if src_key in params:
        target[dst_key] = params[src_key]


def _srw_pp_to_simplified(pp: list) -> dict:
    """Convert an SRW 17-element propagation parameter array to our 5-parameter format.

    SRW array indices:
        [3] → mode (semi-analytical quadratic phase treatment: 0-4)
        [4] → Fourier-side resize flag (affects mode 3/4 detection)
        [5] → horizontal range factor
        [6] → horizontal resolution factor
        [7] → vertical range factor
        [8] → vertical resolution factor
    """
    mode_val = int(pp[3]) if len(pp) > 3 else 0
    fourier_resize = int(pp[4]) if len(pp) > 4 else 0

    # Determine our simplified mode from the SRW flags
    if fourier_resize:
        # Modes 3/4 use Fourier-side resizing; we can't distinguish 3 vs 4
        # from the pp array alone, so default to 3
        mode = 3
    else:
        mode = mode_val  # 0, 1, or 2

    return {
        "mode": mode,
        "range_x": pp[5] if len(pp) > 5 else 1.0,
        "resolution_x": pp[6] if len(pp) > 6 else 1.0,
        "range_y": pp[7] if len(pp) > 7 else 1.0,
        "resolution_y": pp[8] if len(pp) > 8 else 1.0,
    }


def _stub_srw_execution(source_text: str) -> str:
    """Modify script source so it can be executed without SRW or running main().

    We prepend stubs for srwpy imports and replace the ``main()`` / ``epilogue()``
    calls at module level so the script doesn't attempt actual simulations.
    """
    stub_preamble = '''
import sys as _sys

# Stub out SRW modules so the script can be parsed without srwpy installed
class _StubModule:
    def __getattr__(self, name):
        return _StubModule()
    def __call__(self, *a, **kw):
        return _StubModule()

for _mod_name in ['srwpy', 'srwpy.srwl_bl', 'srwpy.srwlib', 'srwpy.srwlpy',
                   'srwpy.srwl_uti_smp', 'srwlib', 'srwl_bl']:
    if _mod_name not in _sys.modules:
        _sys.modules[_mod_name] = _StubModule()

'''
    # Comment out main()/epilogue() calls at module level to prevent execution
    # These are typically bare calls like "main()" or "epilogue()" at column 0
    modified = re.sub(r'^(main\(\))', r'# \1  # stubbed', source_text, flags=re.MULTILINE)
    modified = re.sub(r'^(epilogue\(\))', r'# \1  # stubbed', modified, flags=re.MULTILINE)

    return stub_preamble + modified
